### ISSUE TITLE
Trying to remove last system if you are not connected to it, causes console error

### ISSUE THREAD

**Issue by JulieMarie** [Teradata/vantage-ui-platform#114]
If there is only one system and you are not currently connected to it and you are trying to remove it, you will get a console error here:  https://github.com/Teradata/vantage-ui-platform/blob/68ec52eae6d01a85745a3acdb50f81b7b5640489/src/lib/sqle/connection.service.ts#L175-177

**Comment by JulieMarie** [comment]
No longer an issue

**Comment by christianmemije** [comment]
@JulieMarie How was it fixed?

**Comment by JulieMarie** [comment]
Don't know to be honest @christianmemije. I went to fix it and couldn't recreate it here on the platform.  Then went back to editor and removed that excess code that was confusing and can't recreate it on editor now either.
