### ISSUE TITLE
Add Teradata-specific icon font

### ISSUE THREAD

**Issue by adamnel** [Teradata/vantage-ui-platform#56]
In addition to the Material icons, we need to have a set of icons for use when referencing internal items. For example, custom icons for data types, apps, operations, etc that aren't covered by the default or Covalent sets.

Probably should be kept separate from the Covalent icon font, due to its specificity - it'll be pretty unique to our use cases.

**Comment by adamnel** [comment]
Rather than an icon font, can we use Angular Material's `MatIconRegistry` with an SVG sprite so that we:

a) Have only one http request
b) Can include animation

We did this in the TDAA library, hopefully might be simple lift-and-shift.

**Comment by adamnel** [comment]
Could combine with #57 so that we only have to add updated sprites for the icons that need a dark mode variant, and allow the browser to do the swap based on theme. Still all in a single http request.

**Comment by kyleledbetter** [comment]
Would you need dark mode variants for icons? They can be styled via CSS utility color classes right @adamnel ?

**Comment by kyleledbetter** [comment]
also for the MatIconRegistry, there's already a folder using this method here in the template https://github.com/Teradata/vantage-ui-template/tree/master/src/assets/icons where you can add more single or sprite icons

**Comment by adamnel** [comment]
> Would you need dark mode variants for icons? They can be styled via CSS utility color classes right @adamnel ?

Yeah maybe these two could be combined into the same ticket since they're so tightly coupled.

> also for the MatIconRegistry, there's already a folder using this method here in the template https://github.com/Teradata/vantage-ui-template/tree/master/src/assets/icons where you can add more single or sprite icons

Maybe we just copy/move this to the vantage-ui-platform repo so that we can make updates as we add to the icon set and push it to the consuming apps?

**Comment by adamnel** [comment]
Got it working: https://github.com/Teradata/vantage-ui-platform/tree/feat/theme-tweaks
