### ISSUE TITLE
Add ability to automatically swap icon set for light vs dark modes

### ISSUE THREAD

**Issue by adamnel** [Teradata/vantage-ui-platform#57]
Many times the illustration for dark-on-light vs light-on-dark needs to be subtly different to convey the right meaning. 

Automatically swap out icon set with a dark mode version when in dark mode.

**Possible implementation**
SVG sprite with Angular Material's `MatIconRegistry` paired with the following:
https://blog.tomayac.com/2019/09/21/prefers-color-scheme-in-svg-favicons-for-dark-mode-icons/

**Comment by kyleledbetter** [comment]
i mentioned this on https://github.com/Teradata/vantage-ui-platform/issues/56 but with the dark and light mode themes you already dynamically change the color values for text or svg fill colors, so there's no need to change the actual SVG icon, just toggle the theme and the color should work on dark or light based on your theme and utility classes

**Comment by adamnel** [comment]
I was wondering if I was explaining that properly. It's not about the color, it's about the actual icons. For example:

![image](https://user-images.githubusercontent.com/1143267/75072537-aa428c80-54c5-11ea-9885-5aab18eeaa12.png)

**Comment by kyleledbetter** [comment]
Ah I see so it's changing from outline to fill and stuff like that... That would require changing out sprites and or icon fonts based on the theme then like you were thinking

**Comment by adamnel** [comment]
Got it working: #58
