### ISSUE TITLE
Add theme-based icon swapping based on user theme preference

### ISSUE THREAD

**Issue by adamnel** [Teradata/vantage-ui-platform#69]
Icons currently swap based on OS preference, but if the user chooses a theme manually, they don't respect this setting.

**Comment by christianmemije** [comment]
Right, you should be able to just adjust the icon css to rely on `.dark-theme` and `.light-theme` classes that are added to the html tag within our theme service.

**Comment by jeremysmartt** [comment]
closed via #80
