### ISSUE TITLE
Does it work with only Teradata vantage or can be used with Teradata database as well?

### ISSUE THREAD

**Issue by subbareddydagumati** [Teradata/vantage-ui-platform#97]

**Comment by jeremysmartt** [comment]
There might be pieces and parts in here that can work without Vantage, however the intent of this repository is to be used within a Vantage environment.  Many of the calls to services for example SSO, Auth, Notifications, and others assume that the parts of the platform are available.  With Vantage those parts of the platform are there and ready for use.
